print(r"   /`\___/`\  ")
print(r" (   o   o   ) ")
print(r"  \    *    /")
print(r"   \  ---╯ /")
print(r"    \     /")
print(r"     > ^ <  ")
print(r"    /     \ ")
print(r"   /       \ ")
print(r"  /   | |   \ ")
print(r" (    | |    )")
print(r"  \   | |   / ")
print(r"   \  | |  /  ")
print(r"    \_|_|_/   ")