print(r"          |\___/| ")
print(r"          )     ( ")
print(r"         =\     /= ")
print(r"           )===( ")
print(r"          /     \ ")
print(r"          |     | ")
print(r"         /       \ ")
print(r"         \       / ")
print(r"  _/\_/\_/\__  _/_/\_/\_/\_ ")
print(r"  |  |  |  |( (  |  |  |  | ")
print(r"  |  |  |  | ) ) |  |  |  | ")
print(r"  |  |  |  |(_(  |  |  |  | ")
print(r"  |  |  |  |  |  |  |  |  | ")